import { CaseSummary } from './types';

interface CaseInfo {
  case_name: string;
  court_name: string;
  court_id: string;
  jurisdiction_type: string;
  date_filed: string | null;
  date_decided: string | null;
  status: string;
  docket_number: string;
  nature_of_suit: string;
  judges: string[];
  category: string;
  state: string;
  source_url: string;
  matched_keywords: string[];
  summary: CaseSummary | null;
}

const CATEGORY_LABELS: Record<string, string> = {
  foia: 'FOIA Request',
  sunshine: 'Sunshine / Open Records',
  missing_data: 'Missing or Destroyed Records',
  access_denied: 'Access Denied / Withheld',
  other: 'Public Records Related',
};

const SEVERITY_LABELS: Record<string, string> = {
  high: '!!',
  medium: '!',
  low: '~',
};

export function generateCaseReport(caseInfo: CaseInfo): string {
  const lines: string[] = [];
  const divider = '='.repeat(60);
  const subDivider = '-'.repeat(40);

  lines.push(divider);
  lines.push('CASE ANALYSIS REPORT');
  lines.push(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(divider);
  lines.push('');

  // Case identification
  lines.push('CASE IDENTIFICATION');
  lines.push(subDivider);
  lines.push(`Case Name: ${caseInfo.case_name}`);
  lines.push(`Court: ${caseInfo.court_name || caseInfo.court_id || 'Unknown'}`);
  lines.push(`Docket Number: ${caseInfo.docket_number || 'N/A'}`);
  lines.push(`Category: ${CATEGORY_LABELS[caseInfo.category] || caseInfo.category || 'N/A'}`);
  lines.push(`Jurisdiction: ${caseInfo.jurisdiction_type || 'N/A'}`);
  if (caseInfo.state) lines.push(`State: ${caseInfo.state}`);
  lines.push(`Date Filed: ${caseInfo.date_filed || 'N/A'}`);
  lines.push(`Date Decided: ${caseInfo.date_decided || 'N/A'}`);
  lines.push(`Status: ${caseInfo.status || 'N/A'}`);
  if (caseInfo.judges?.length > 0 && caseInfo.judges[0]) {
    lines.push(`Judge(s): ${caseInfo.judges.join(', ')}`);
  }
  if (caseInfo.nature_of_suit) lines.push(`Nature of Suit: ${caseInfo.nature_of_suit}`);
  if (caseInfo.source_url) lines.push(`Source: ${caseInfo.source_url}`);
  lines.push('');

  if (caseInfo.summary) {
    const s = caseInfo.summary;

    // Flags (prominent placement)
    if (s.flags.length > 0) {
      lines.push('JOURNALIST FLAGS');
      lines.push(subDivider);
      for (const flag of s.flags) {
        lines.push(`[${SEVERITY_LABELS[flag.severity]}] ${flag.label}`);
        lines.push(`    ${flag.description}`);
      }
      lines.push('');
    }

    // Key facts
    if (s.key_facts.length > 0) {
      lines.push('KEY FACTS');
      lines.push(subDivider);
      for (const fact of s.key_facts) {
        lines.push(`• ${fact}`);
      }
      lines.push('');
    }

    // Outcome
    lines.push('OUTCOME');
    lines.push(subDivider);
    lines.push(s.outcome);
    lines.push('');

    // Parties
    if (s.parties.length > 0) {
      lines.push('PARTIES');
      lines.push(subDivider);
      lines.push(s.parties.join(', '));
      lines.push('');
    }

    // Legal issues
    if (s.legal_issues.length > 0) {
      lines.push('LEGAL ISSUES');
      lines.push(subDivider);
      for (const issue of s.legal_issues) {
        lines.push(`• ${issue}`);
      }
      lines.push('');
    }

    // Timeline
    if (s.timeline.length > 0) {
      lines.push('TIMELINE');
      lines.push(subDivider);
      for (const event of s.timeline) {
        lines.push(`${event.date}: ${event.description}`);
      }
      lines.push('');
    }

    lines.push(`[Summary generated via ${s.method === 'claude_api' ? 'Claude AI' : 'automated extraction'} on ${new Date(s.generated_at).toLocaleDateString()}]`);
  }

  // Keywords
  if (caseInfo.matched_keywords?.length > 0) {
    lines.push('');
    lines.push('MATCHED KEYWORDS');
    lines.push(subDivider);
    lines.push(caseInfo.matched_keywords.join(', '));
  }

  lines.push('');
  lines.push(divider);
  lines.push('Report generated by SunshineTracker');
  lines.push(divider);

  return lines.join('\n');
}

export function generateFoiaTemplate(caseInfo: CaseInfo): string {
  const lines: string[] = [];
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Determine agency from case details
  const agencyName = extractAgencyName(caseInfo);
  const recordsDescription = buildRecordsDescription(caseInfo);
  const legalBasis = buildLegalBasis(caseInfo);
  const flagJustification = buildFlagJustification(caseInfo);

  lines.push(today);
  lines.push('');
  lines.push(`FOIA Officer`);
  lines.push(`${agencyName}`);
  lines.push('[Agency Address]');
  lines.push('[City, State ZIP]');
  lines.push('');
  lines.push('Re: Freedom of Information Act Request');
  lines.push('');
  lines.push('Dear FOIA Officer:');
  lines.push('');
  lines.push(`Pursuant to the Freedom of Information Act, 5 U.S.C. § 552, I am requesting access to and copies of the following records:`);
  lines.push('');
  lines.push(recordsDescription);
  lines.push('');

  // Legal basis citing the case
  lines.push(legalBasis);
  lines.push('');

  // Flag-based justification
  if (flagJustification) {
    lines.push(flagJustification);
    lines.push('');
  }

  lines.push('I am a representative of the news media and this request is made as part of news gathering and not for commercial use. I am requesting a fee waiver because disclosure of the requested information is in the public interest, as it is likely to contribute significantly to public understanding of government operations or activities.');
  lines.push('');
  lines.push('I am willing to pay reasonable duplication fees for the processing of this request in an amount not to exceed $25.00. Please notify me prior to your incurring any expenses in excess of that amount.');
  lines.push('');
  lines.push('If my request is denied in whole or in part, I ask that you justify all deletions by reference to specific exemptions of the Act. I also expect you to release all segregable portions of otherwise exempt material.');
  lines.push('');
  lines.push('I look forward to your response within 20 business days, as required by law.');
  lines.push('');
  lines.push('Thank you for your assistance.');
  lines.push('');
  lines.push('Sincerely,');
  lines.push('');
  lines.push('[Your Name]');
  lines.push('[Your Organization]');
  lines.push('[Your Address]');
  lines.push('[Your Email]');
  lines.push('[Your Phone]');
  lines.push('');
  lines.push('---');
  lines.push(`Reference Case: ${caseInfo.case_name}`);
  if (caseInfo.docket_number) lines.push(`Docket: ${caseInfo.docket_number}`);
  if (caseInfo.court_name) lines.push(`Court: ${caseInfo.court_name}`);
  lines.push('Generated by SunshineTracker');

  return lines.join('\n');
}

function extractAgencyName(caseInfo: CaseInfo): string {
  // Try to extract agency name from case name (usually the defendant in FOIA cases)
  const vMatch = caseInfo.case_name.match(/v\.?\s+(.+?)(?:\s*$|\s*,)/);
  if (vMatch) {
    const defendant = vMatch[1].trim();
    // Common agency abbreviations suggest a government entity
    if (/\b(?:Department|Agency|Bureau|Office|Commission|Administration|Service|Board)\b/i.test(defendant)) {
      return defendant;
    }
    // If it looks like a government entity (contains U.S., United States, etc.)
    if (/\b(?:U\.?S\.?|United\s+States|Federal|State\s+of)\b/i.test(defendant)) {
      return defendant;
    }
    return defendant;
  }
  return '[Agency Name]';
}

function buildRecordsDescription(caseInfo: CaseInfo): string {
  const parts: string[] = [];

  if (caseInfo.category === 'foia' || caseInfo.category === 'access_denied') {
    parts.push(`All records, documents, communications, and correspondence related to the matters at issue in ${caseInfo.case_name}`);
    if (caseInfo.docket_number) {
      parts.push(` (Docket No. ${caseInfo.docket_number})`);
    }
    parts.push('.');
  } else if (caseInfo.category === 'missing_data') {
    parts.push(`All records pertaining to the alleged missing, destroyed, or unreleased records referenced in ${caseInfo.case_name}. This includes any retention schedules, destruction logs, preservation orders, and communications regarding the disposition of these records.`);
  } else {
    parts.push(`All records, documents, and communications related to the subject matter of ${caseInfo.case_name}`);
    if (caseInfo.nature_of_suit) {
      parts.push(` (Nature of Suit: ${caseInfo.nature_of_suit})`);
    }
    parts.push('.');
  }

  return parts.join('');
}

function buildLegalBasis(caseInfo: CaseInfo): string {
  const parts: string[] = [];

  parts.push(`This request is supported by the legal precedent established in ${caseInfo.case_name}`);
  if (caseInfo.court_name) {
    parts.push(` (${caseInfo.court_name}`);
    if (caseInfo.date_decided) {
      parts.push(`, decided ${caseInfo.date_decided}`);
    }
    parts.push(')');
  }
  parts.push('.');

  if (caseInfo.summary?.outcome) {
    parts.push(` In that case, the court found: "${caseInfo.summary.outcome}"`);
  }

  return parts.join('');
}

function buildFlagJustification(caseInfo: CaseInfo): string | null {
  if (!caseInfo.summary?.flags?.length) return null;

  const lines: string[] = [];
  lines.push('This request is particularly urgent given the following issues identified in the referenced case:');
  lines.push('');

  for (const flag of caseInfo.summary.flags) {
    if (flag.type === 'record_destruction') {
      lines.push('• Evidence of record destruction or spoliation has been identified, creating heightened urgency for the preservation and production of any remaining records.');
    } else if (flag.type === 'ephemeral_messaging') {
      lines.push('• The case references the use of ephemeral messaging platforms, raising concerns about the preservation of official communications as required by federal records laws.');
    } else if (flag.type === 'unreasonable_delay') {
      lines.push('• The underlying case reflects an unreasonable delay in the adjudication process, underscoring the need for timely production of responsive records.');
    } else if (flag.type === 'exemption_overuse') {
      lines.push('• The case involves the citation of multiple FOIA exemptions, suggesting a pattern of broad withholding that warrants scrutiny.');
    }
  }

  return lines.join('\n');
}
